services:
  nexus:
    image: sonatype/nexus3:3.82.0
    container_name: nexus
    ports:
      - 8081:8081
      - 8344:8344
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - INSTALL4J_ADD_VM_PARAMS=-Dnexus.scripts.allowCreation=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

volumes:
  nexus-data:
